version: '3'

services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5001
    restart: always
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge